from __future__ import annotations

import re
from pathlib import Path

from .capture import capture_session
from .models import SessionPaths
from .text_utils import compact_list, slugify


COMMAND_PREFIXES = (
    "./",
    "bash ",
    "cargo ",
    "cmake ",
    "codex ",
    "Debug/",
    "gh ",
    "git ",
    "make ",
    "make -C ",
    "npm ",
    "python ",
    "python3 ",
    "pytest",
    "scons ",
    "vibewiki ",
)

TEST_HINTS = (
    "pass",
    "passed",
    "resource check",
    "exit code 0",
    "mismatch",
    "mae",
    "rmse",
    "relative rmse",
    "验证",
    "通过",
    "失败",
    "误差",
)

BENCHMARK_HINTS = (
    "benchmark",
    "throughput",
    "latency",
    "power",
    "energy",
    "rmse",
    "mae",
    "signal rms",
    "relative rmse",
    "性能",
    "功耗",
    "吞吐",
    "能效",
)


def first_heading(markdown: str) -> str:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return ""


def likely_outcome(markdown: str) -> str:
    lines = [line.strip() for line in markdown.splitlines()]
    candidates: list[str] = []
    for line in lines:
        clean = line.lstrip("> ").strip()
        if clean.startswith(("结论：", "结论:", "已改好", "改好了", "可以，已经")):
            candidates.append(clean)
        if len(candidates) >= 4:
            break
    return "\n".join(candidates)


def _candidate_command(line: str) -> str:
    stripped = line.strip()
    if stripped.startswith("- "):
        stripped = stripped[2:].strip()
    if stripped.startswith("> "):
        stripped = stripped[2:].strip()
    stripped = stripped.strip("`")
    if any(stripped.startswith(prefix) for prefix in COMMAND_PREFIXES):
        return stripped
    return ""


def extract_commands(markdown: str, limit: int = 12) -> list[str]:
    commands: list[str] = []
    in_fence = False
    fence_language = ""

    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            if not in_fence:
                in_fence = True
                fence_language = stripped.strip("`").strip().lower()
            else:
                in_fence = False
                fence_language = ""
            continue

        command = ""
        if in_fence and fence_language in {"", "bash", "sh", "shell", "console", "text"}:
            command = _candidate_command(stripped)
        elif "`" in stripped:
            for match in re.findall(r"`([^`]+)`", stripped):
                command = _candidate_command(match)
                if command:
                    break
        else:
            command = _candidate_command(stripped)

        if command and command not in commands:
            commands.append(command)
        if len(commands) >= limit:
            break

    return commands


def extract_hint_lines(markdown: str, hints: tuple[str, ...], limit: int = 12) -> list[str]:
    found: list[str] = []
    for line in markdown.splitlines():
        clean = line.strip().lstrip("> ").strip()
        if not clean or clean.startswith("<details"):
            continue
        lowered = clean.lower()
        if any(hint in lowered for hint in hints):
            if len(clean) > 220:
                clean = clean[:217] + "..."
            if clean not in found:
                found.append(clean)
        if len(found) >= limit:
            break
    return found


def render_import_summary(source: Path, title: str, outcome: str) -> str:
    details = [
        f"Imported from Markdown source: `{source}`.",
        "The full original conversation is preserved as `raw_session.md`.",
        "This normalized record was generated by local heuristics and should be reviewed.",
    ]
    if title:
        details.append(f"Detected title: {title}")
    if outcome:
        details.append("Detected outcome signals are listed in Final Outcome.")
    return "\n".join(f"- {item}" for item in details)


def import_markdown_session(
    project: Path,
    source: Path,
    *,
    goal: str = "",
    outcome: str = "",
    commands: list[str] | None = None,
    tests: str = "",
    benchmark: str = "",
    notes: str = "",
    things_not_to_record: str = "",
    session_name: str | None = None,
) -> SessionPaths:
    source_path = source.expanduser().resolve()
    markdown = source_path.read_text(encoding="utf-8")
    title = first_heading(markdown)
    inferred_goal = goal or title or source_path.stem
    inferred_outcome = outcome or likely_outcome(markdown)
    inferred_commands = compact_list([*(commands or []), *extract_commands(markdown)])
    inferred_tests = tests or "\n".join(extract_hint_lines(markdown, TEST_HINTS))
    inferred_benchmark = benchmark or "\n".join(extract_hint_lines(markdown, BENCHMARK_HINTS))
    summary = render_import_summary(source_path, title, inferred_outcome)
    session_slug = session_name or slugify(inferred_goal, fallback=source_path.stem)

    paths = capture_session(
        project,
        goal=inferred_goal,
        outcome=inferred_outcome,
        commands=inferred_commands,
        tests=inferred_tests,
        benchmark=inferred_benchmark,
        notes=notes,
        ai_summary=summary,
        things_not_to_record=things_not_to_record,
        session_name=session_slug,
    )

    raw_session = paths.session_dir / "raw_session.md"
    raw_session.write_text(markdown, encoding="utf-8")

    metadata = paths.metadata_yaml.read_text(encoding="utf-8")
    metadata += f"imported_from: {source_path}\nraw_session: {raw_session}\n"
    paths.metadata_yaml.write_text(metadata, encoding="utf-8")
    return paths
